BRUTE_FORCE_THRESHOLD = 5
BRUTE_FORCE_INTERVAL_MINUTES = 5

RESOURCE_ENUMERATION_THRESHOLD = 6
RESOURCE_ENUMERATION_INTERVAL_MINUTES = 15

CREDENTIAL_STUFFING_THRESHOLD = 5
CREDENTIAL_STUFFING_INTERVAL_MINUTES = 10

ALERT_COOLDOWN_MINUTES = 5

CORRELATION_INTERVAL_MINUTES = 10

PASSWORD_SPRAYING_THRESHOLD = 5
PASSWORD_SPRAYING_INTERVAL_MINUTES = 10